### ISSUE TITLE
unknown error 

### ISSUE THREAD

**Issue by xGoldaxe** [restray/ft_transcendance#19]
Fichier: [src/prisma/user/userfields.interceptor.ts:23:26](https://github.com/restray/ft_transcendance/blob/42f7c8c58757bc48b9e648c58e83ea0cc86eb28b/backend/src/prisma/user/userfields.interceptor.ts#L23)
```
[Nest] 420020  - 07/13/2022, 3:42:58 PM   ERROR [ExceptionsHandler] Cannot delete property '0' of [object String]
TypeError: Cannot delete property '0' of [object String]
    at getObject (/mnt/nfs/homes/pleveque/Documents/test/backend/src/prisma/user/userfields.interceptor.ts:23:26)
    at /mnt/nfs/homes/pleveque/Documents/test/backend/src/prisma/user/userfields.interceptor.ts:42:16
    at /mnt/nfs/homes/pleveque/Documents/test/backend/node_modules/rxjs/src/internal/operators/map.ts:58:33
    at OperatorSubscriber._this._next (/mnt/nfs/homes/pleveque/Documents/test/backend/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
    at OperatorSubscriber.Subscriber.next (/mnt/nfs/homes/pleveque/Documents/test/backend/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
    at /mnt/nfs/homes/pleveque/Documents/test/backend/node_modules/rxjs/src/internal/operators/mergeInternals.ts:85:24
    at OperatorSubscriber._this._next (/mnt/nfs/homes/pleveque/Documents/test/backend/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
    at OperatorSubscriber.Subscriber.next (/mnt/nfs/homes/pleveque/Documents/test/backend/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
    at /mnt/nfs/homes/pleveque/Documents/test/backend/node_modules/rxjs/src/internal/operators/switchMap.ts:115:42
    at OperatorSubscriber._this._next (/mnt/nfs/homes/pleveque/Documents/test/backend/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
[Nest] 420020  - 07/13/2022, 3:43:23 PM   ERROR [ExceptionsHandler] Cannot delete property '0' of [object String]
TypeError: Cannot delete property '0' of [object String]
    at getObject (/mnt/nfs/homes/pleveque/Documents/test/backend/src/prisma/user/userfields.interceptor.ts:23:26)
    at /mnt/nfs/homes/pleveque/Documents/test/backend/src/prisma/user/userfields.interceptor.ts:42:16
    at /mnt/nfs/homes/pleveque/Documents/test/backend/node_modules/rxjs/src/internal/operators/map.ts:58:33
    at OperatorSubscriber._this._next (/mnt/nfs/homes/pleveque/Documents/test/backend/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
    at OperatorSubscriber.Subscriber.next (/mnt/nfs/homes/pleveque/Documents/test/backend/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
    at /mnt/nfs/homes/pleveque/Documents/test/backend/node_modules/rxjs/src/internal/operators/mergeInternals.ts:85:24
    at OperatorSubscriber._this._next (/mnt/nfs/homes/pleveque/Documents/test/backend/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
    at OperatorSubscriber.Subscriber.next (/mnt/nfs/homes/pleveque/Documents/test/backend/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
    at /mnt/nfs/homes/pleveque/Documents/test/backend/node_modules/rxjs/src/internal/operators/switchMap.ts:115:42
    at OperatorSubscriber._this._next (/mnt/nfs/homes/pleveque/Documents/test/backend/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
[Nest] 420020  - 07/13/2022, 3:43:29 PM   ERROR [ExceptionsHandler] Cannot delete property '0' of [object String]
TypeError: Cannot delete property '0' of [object String]
    at getObject (/mnt/nfs/homes/pleveque/Documents/test/backend/src/prisma/user/userfields.interceptor.ts:23:26)
    at /mnt/nfs/homes/pleveque/Documents/test/backend/src/prisma/user/userfields.interceptor.ts:42:16
    at /mnt/nfs/homes/pleveque/Documents/test/backend/node_modules/rxjs/src/internal/operators/map.ts:58:33
    at OperatorSubscriber._this._next (/mnt/nfs/homes/pleveque/Documents/test/backend/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
    at OperatorSubscriber.Subscriber.next (/mnt/nfs/homes/pleveque/Documents/test/backend/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
    at /mnt/nfs/homes/pleveque/Documents/test/backend/node_modules/rxjs/src/internal/operators/mergeInternals.ts:85:24
    at OperatorSubscriber._this._next (/mnt/nfs/homes/pleveque/Documents/test/backend/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
    at OperatorSubscriber.Subscriber.next (/mnt/nfs/homes/pleveque/Documents/test/backend/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
    at /mnt/nfs/homes/pleveque/Documents/test/backend/node_modules/rxjs/src/internal/operators/switchMap.ts:115:42
    at OperatorSubscriber._this._next (/mnt/nfs/homes/pleveque/Documents/test/backend/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
```

**Comment by restray** [comment]
Je m'en occupe, c'est une erreur sur un filtre sur les réponses.
L'objectif du filtre est de retirer les champs qu'un utilisateur ne doit jamais avoir! (comme `password` ou `otp_secret` notamment)
